[package]
authors.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
name = "common"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
dotenv.workspace = true
