[package]
edition = "2021"
name = "xml2"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
Inflector = "0.11"
anyhow = "1.0"
bigdecimal = "0.4"
chrono = "0.4"
num-bigint = "0.4"
roxmltree = "0.20"
syn = { version = "2", features = ["extra-traits", "full"] }
text-diff = "0.4"
xml-rs = "0.8"
xml2-macro = { path = "../xml2-macro" }
yaserde = "0.12"
yaserde_derive = "0.12"
