networks:
  reearth-flow-net:
    external: true

services:
  redis:
    image: redis:7
    container_name: subscriber-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - reearth-flow-net

  subscriber:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: subscriber
    restart: always
    depends_on:
      - redis
    networks:
      - reearth-flow-net
    environment:
      - REEARTH_FLOW_SUBSCRIBER_PROJECT_ID=${REEARTH_FLOW_SUBSCRIBER_PROJECT_ID}
      - REEARTH_FLOW_SUBSCRIBER_SUBSCRIPTION_ID=${REEARTH_FLOW_SUBSCRIBER_SUBSCRIPTION_ID}
      - REEARTH_FLOW_SUBSCRIBER_REDIS_URL=redis://:${REEARTH_FLOW_SUBSCRIBER_REDIS_PASSWORD}@redis:6379
