networks:
  reearth-flow-net:
    external: true

services:
  redis:
    image: redis:7
    container_name: subscriber-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - reearth-flow-net

  subscriber:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: subscriber
    restart: always
    depends_on:
      - redis
    networks:
      - reearth-flow-net
    environment:
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - REDIS_URL=redis://localhost:6379
      - SUBSCRIPTION_ID=${SUBSCRIPTION_ID}
