[package]
description = "Re:Earth Flow Websocket Domain library"
name = "infra"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
common = { path = "../common" }
services = { path = "../services" }

flow-websocket-domain.workspace = true

async-trait.workspace = true
axum.workspace = true
axum-extra.workspace = true
axum-macros.workspace = true
base64.workspace = true
cached.workspace = true
chrono.workspace = true
dotenv.workspace = true
futures-util.workspace = true
google-cloud-storage.workspace = true
lru.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
jsonwebtoken.workspace = true
once_cell.workspace = true
rand.workspace = true
>>>>>>> 1c5a483 (Format TOML files using taplo)
redis.workspace = true
reqwest.workspace = true
rsa.workspace = true
rslock.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
wiremock.workspace = true
yrs.workspace = true
