[package]
name = "services"
authors.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
tokio.workspace = true
axum.workspace = true
reqwest.workspace = true
http.workspace = true
thiserror.workspace = true
wiremock.workspace = true
tower.workspace = true
