[workspace]
members = ["crates/*"]

resolver = "2"

[workspace.package]
authors = ["Re:Earth Flow Contributors"]
edition = "2021"
exclude = ["benches/", "test-data/", "testdata/"]
homepage = "https://github.com/reearth/reearth-flow/websocket"
license = "MIT OR Apache-2.0"
repository = "https://github.com/reearth/reearth-flow/websocket"
rust-version = "1.78"
version = "0.1.0"

[profile.dev]
opt-level = 0

# Like release, but with full debug symbols and with stack unwinds. Useful for e.g. `perf`.
[profile.debug-fast]
debug = true
incremental = false
inherits = "release"
panic = "unwind"
strip = "none"

# Optimized release profile
[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
strip = true

[workspace.dependencies]
flow-websocket-domain = { path = "crates/domain" }

async-trait = "0.1.80"
axum = { version = "0.7", features = ["ws"] }
axum-extra = { version = "0.9", features = ["typed-header"] }
axum-macros = "0.4"
base64 = "0.22.1"
cached = "0.53.1"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15.0"
futures-util = "0.3"
google-cloud-storage = "0.18"
http = "1.1.0"
http-body-util = "0.1.0"
hyper = "1.4.1"
jsonwebtoken = "9.3.0"
lru = "0.12.4"
once_cell = "1.18.0"
rand = "0.8"
redis = { version = "0.25.4", features = ["aio", "tokio-comp"] }
reqwest = { version = "0.12.7", features = ["json"] }
rsa = { version = "0.9.6", features = ["pem"] }
rslock = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.117", features = ["arbitrary_precision"] }
tempfile = "3.12.0"
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["full", "time"] }
tokio-tungstenite = "0.24.0"
tower = { version = "0.4", features = ["timeout"] }
tower-http = { version = "0.5", features = ["fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5.2"
uuid = { version = "1.8.0", features = ["fast-rng", "macro-diagnostics", "serde", "v4"] }
wiremock = "0.6.2"
yrs = "0.18"
