services:
  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - fake-gcs

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  fake-gcs:
    image: fsouza/fake-gcs-server
    ports:
      - "4443:4443"
    command: ["-scheme", "http"]
    volumes:
      - gcs-data:/data

volumes:
  gcs-data:
