version: "3"
services:
  reearth-flow-api:
    build: .
    environment:
      REEARTH_FLOW_DB: mongodb://reearth-flow-mongo
    ports:
      - "8081:8080"
    # env_file:
    #  - ./.env
    depends_on:
      - reearth-flow-mongo

  reearth-flow-mongo:
    image: mongo:6-focal
    volumes:
      - type: volume
        source: reearth-flow-mongo
        target: /data/db
        volume:
          nocopy: true
    command: mongod --port 27017 --bind_ip_all

volumes:
  reearth-flow-mongo:
    driver: local
